# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: broker_service.proto for package 'pinot.broker.grpc'

require 'grpc'
require_relative 'broker_service_pb'

module Pinot
  module Broker
    module Grpc
      module PinotClientGrpcBrokerService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'pinot.broker.grpc.PinotClientGrpcBrokerService'

          rpc :Submit, ::Pinot::Broker::Grpc::BrokerRequest, ::Pinot::Broker::Grpc::BrokerResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
